config/routes.rb
Rails.application.routes.draw do

  get 'admin_panel/users'

  get 'admin_panel/edit_role'
  post 'admin_panel/update_role'
  
  get 'tracks/display_map'
  get 'tracks/getallroutesformap'
  get 'tracks/getrouteformap'
  get 'tracks/getroutes'
  post 'tracks/updatelocation'
  get 'tracks/deleteroute'
  
    
  devise_for :users, :controllers => {sessions: 'sessions', :passwords => "passwords"}
  

resources :users

  resources :schools

  resources :stops do
  collection do
      post  :create_route_stops
    end
  end

  resources :routes do
   collection do
      get  :user_routes
    end
  end

  resources :devices

  resources :vehicles do
   collection do
      get  :user_vehicles
    end
  end
  root 'tracks#display_map'
  

end

app/models/stop.rb
class Stop < ActiveRecord::Base
  belongs_to :route
  validates :latitude,:longitude, :presence => true  
  attr_accessor :gpstime
  # before_save :assign_name 
  reverse_geocoded_by :latitude, :longitude,  :address => :name
  after_validation :reverse_geocode
  
  
  # def check_distance  b
    # a = [self.latitude,self.longitude]
    # rad_per_deg = Math::PI/180  # PI / 180
    # rkm = 6371                  # Earth radius in kilometers
    # rm = rkm * 1000             # Radius in meters
# 
    # dlon_rad = (b[1]-a[1]) * rad_per_deg  # Delta, converted to rad
    # dlat_rad = (b[0]-a[0]) * rad_per_deg
# 
    # lat1_rad, lon1_rad = a.map! {|i| i * rad_per_deg }
    # lat2_rad, lon2_rad = b.map! {|i| i * rad_per_deg }
# 
    # a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
    # c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a))
# 
    # rm * c # Delta in Kilometers
  # end
  
  def check_distance  loc
    return (Geocoder::Calculations.distance_between([self.latitude,self.longitude], loc))/0.00062137
  end
  
  
  # def assign_name
    # unless self.latitude.nil? && self.longitude.nil?
    # self.name = Geocoder.search("#{self.latitude}, #{self.longitude}") unless self.name.nil?
    # puts "(((((((((((((((((((#{Geocoder.search("#{self.latitude}, #{self.longitude}")})))))))))))))))))))"
    # end
  # end

# puts distance [46.3625, 15.114444],[46.055556, 14.508333]
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :set_stop, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:index, :show,:create_route_stops]
  skip_before_filter :verify_authenticity_token,  :only => [:create_route_stops]
  # GET /stops
  # GET /stops.json
  def index
    @routes=Route.where(:vehicle_id => school_vehicles_ids).map(&:id)
    @stops = Stop.where(:route_id => @routes)
  end

  # GET /stops/1
  # GET /stops/1.json
  def show
  end

  # GET /stops/new
  def new
    @stop = Stop.new
    @routes=Route.where(:vehicle_id => school_vehicles_ids)
  end

  # GET /stops/1/edit
  def edit
    @routes=Route.where(:vehicle_id => school_vehicles_ids)
  end

  # POST /stops
  # POST /stops.json
  def create
    @stop = Stop.new(stop_params)

    respond_to do |format|
      if @stop.save
        format.html { redirect_to stops_path, notice: 'Stop was successfully created.' }
        format.json { render :show, status: :created, location: @stop }
      else
        format.html { render :new }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stops/1
  # PATCH/PUT /stops/1.json
  def update
    respond_to do |format|
      if @stop.update(stop_params)
        format.html { redirect_to stops_path, notice: 'Stop was successfully updated.' }
        format.json { render :show, status: :ok, location: @stop }
      else
        format.html { render :edit }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stops/1
  # DELETE /stops/1.json
  def destroy
    @stop.destroy
    respond_to do |format|
      format.html { redirect_to stops_url, notice: 'Stop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def create_route_stops
      @stop_record = Hash.new
      @route=Route.find_by_id(stop_params[:route_id])    
      time_interval=0
      sequence = 1
      @prev_stop= Stop.where(:route_id => @route.id ).last
      unless @prev_stop.nil?
        start_time = Time.parse(@prev_stop.created_at.to_s).localtime
        end_time = Time.now
       
        time_interval = TimeDifference.between(start_time, end_time).in_minutes.to_i
        # time_interval= ((Time.parse(stop_params[:gpstime]) - Time.parse(@prev_stop.created_at.to_s))/60).to_i  #in minutes
        # time_interval=@prev_stop.timeperiod.to_i + time_interval
        sequence = @prev_stop.sequence.to_i + 1
      end      
    
      @stop_record["latitude"]=stop_params[:latitude]
      @stop_record["longitude"]=stop_params[:longitude]
      @stop_record["timeperiod"]=time_interval
      @stop_record["sequence"]=sequence
      @stop_record["route_id"]=stop_params[:route_id]   
      
      @stop=Stop.new(@stop_record)
      if @stop.save
        logger.info "successfully Saved Stop with id #{@stop.id}"
        render :json => {:message=> "Stop Successfuly Saved",:success=> true} 
      else
        logger.info "Error Saving Stop with #{@stop.errors}"
        render :json => {:message=> @stop.errors,:success=> false} 
      end        
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_stop
    @stop = Stop.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def stop_params
    params.require(:stop).permit(:name, :latitude, :longitude, :timeperiod, :sequence, :route_id,:is_stop, :gpstime)
  end
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/stops/_form.html.erb
<%= form_for(@stop) do |f| %>
  <% if @stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
      <% @stop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name,:class=>"form-control",:placeholder =>"Name", :required=> true %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude,:class=>"form-control",:placeholder =>"Latitude", :required=> true %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude,:class=>"form-control",:placeholder =>"Longitude", :required=> true %>
  </div>
  <div class="field">
    <%= f.label :timeperiod %><br>
    <%= f.text_field :timeperiod,:class=>"form-control",:placeholder =>"TimePeriod", :required=> true %>
  </div>
  <div class="field">
    <%= f.label :sequence %><br>
    <%= f.number_field :sequence,:class=>"form-control",:placeholder =>"Sequence", :required=> true %>
  </div>
  <div class="field">
    <%= f.label :route_id %><br>
    <%= f.select(:route_id ,@routes.map {|c| [c.name, c.id]} ,{:prompt => "Select"}, {:class=>"form-control"})%>
  </div>
  <div class="field">
    <%= f.label :is_stop %><br>
    <%= f.check_box :is_stop %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "submit", :class=> "btn btn-primary btn-lg btn-block"%>
  </div>
<% end %>

app/views/stops/edit.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<h1>Editing Stop</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @stop %> |
		<%= link_to 'Back', stops_path %>
	</div>
</div>

app/views/stops/index.html.erb
<h1>Listing stops</h1>

<table class="table table-striped table-bordered" id= "datatable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Timeperiod</th>
      <th>Sequence</th>
      <th>Route</th>
      <th>Is stop</th>
      <th>
      <% if current_user.role == "superuser" || current_user.role == "admin"%>
      
      <% end %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @stops.each do |stop| %>
      <tr>
        <td><%= stop.name %></td>
        <td><%= stop.latitude %></td>
        <td><%= stop.longitude %></td>
        <td><%= stop.timeperiod %></td>
        <td><%= stop.sequence %></td>
        <td><%= stop.route.name %></td>
        <td><%= stop.is_stop %></td>
         <td>
         <% if current_user.role == "superuser" || current_user.role == "admin"%>
        <%= link_to 'Edit', edit_stop_path(stop) %>
        <% end %>
        <% if current_user.role == "superuser"%>
        <%= link_to 'Destroy', stop, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 <% if current_user.role == "superuser" || current_user.role == "admin"%>
<%= link_to 'New Stop', new_stop_path %>
<% end %>

<script>
	$(document).ready(function(){
		$('#datatable').dataTable({			
			
		});
		
	});
	
</script>

app/views/stops/new.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4 well">
		<h1>New Stop</h1>

		<%= render 'form' %>

		<%= link_to 'Back', stops_path %>
	</div>
</div>

app/views/stops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stop.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @stop.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @stop.longitude %>
</p>

<p>
  <strong>Timeperiod:</strong>
  <%= @stop.timeperiod %>
</p>

<p>
  <strong>Sequence:</strong>
  <%= @stop.sequence %>
</p>

<p>
  <strong>Route:</strong>
  <%= @stop.route %>
</p>
 <% if current_user.role == "superuser" || current_user.role == "admin"%>
<%= link_to 'Edit', edit_stop_path(@stop) %> |
<%end%>
<%= link_to 'Back', stops_path %>