config/routes.rb
Rails.application.routes.draw do

  get 'admin_panel/users'

  get 'admin_panel/edit_role'
  post 'admin_panel/update_role'
  
  get 'tracks/display_map'
  get 'tracks/getallroutesformap'
  get 'tracks/getrouteformap'
  get 'tracks/getroutes'
  post 'tracks/updatelocation'
  get 'tracks/deleteroute'
  
    
  devise_for :users, :controllers => {sessions: 'sessions', :passwords => "passwords"}
  

resources :users

  resources :schools

  resources :stops do
  collection do
      post  :create_route_stops
    end
  end

  resources :routes do
   collection do
      get  :user_routes
    end
  end

  resources :devices

  resources :vehicles do
   collection do
      get  :user_vehicles
    end
  end
  root 'tracks#display_map'
  

end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :vehicles
  has_many :users
  validates :name, :phone_no, :presence => true 
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:index, :show]
  # GET /schools
  # GET /schools.json
  def index
    unless current_user.role == "superuser"
      @schools = current_user.school
    else
      @schools=School.all
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to schools_path, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to schools_path, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :address, :phone_no)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="alert alert-danger" role="alert" style="display:none;"></div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name,:class=>"form-control",:required => true,:placeholder=> "Name"  %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address,:class=>"form-control", :required => true,:placeholder =>"Address"  %>
  </div>
  <div class="field">
    <%= f.label :phone_no %><br>
    <%= f.text_field :phone_no,:class=>"form-control",:required => true,:placeholder =>"Phone No"  %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Submit", :class=> "btn btn-primary " %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>
</div>
</div>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Address</th>
			<th>Phone no</th>
			<% if current_user.role == "superuser" || current_user.role == "admin"%>
			<th colspan="3"></th>
			<%end%>
		</tr>
	</thead>

	<tbody>
		<% if current_user.role == "superuser" %>
		<% @schools.each do |school| %>
		<tr>
			<td><%= school.name %></td>
			<td><%= school.address %></td>
			<td><%= school.phone_no %></td>
			<% if current_user.role == "superuser" || current_user.role == "admin"%>
			<td><%= link_to 'Edit', edit_school_path(school) %></td>
			<%end%>
			<% if current_user.role == "superuser" %>
			<td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			<%end%>
		</tr>
		<% end %>
		<% else%>
		<tr>
			<td><%= @schools.name %></td>
			<td><%= @schools.address %></td>
			<td><%= @schools.phone_no %></td>
			<% if current_user.role == "admin"%>
			<td><%= link_to 'Edit', edit_school_path(@schools) %></td>
			<%end%>
		</tr>
		<% end %>
	</tbody>
</table>

<br>
<% if current_user.role == "superuser"%>
<%= link_to 'New School', new_school_path %>
<%end%>

app/views/schools/new.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4 well">
		<h1>New School</h1>

		<%= render 'form' %>

		<%= link_to 'Back', schools_path %>
	</div>
</div>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @school.address %>
</p>

<p>
  <strong>Phone no:</strong>
  <%= @school.phone_no %>
</p>
<% if current_user.role == "superuser" || current_user.role == "admin"%>
<%= link_to 'Edit', edit_school_path(@school) %> |
<%end%>
<%= link_to 'Back', schools_path %>