config/routes.rb
Rails.application.routes.draw do

  get 'admin_panel/users'

  get 'admin_panel/edit_role'
  post 'admin_panel/update_role'
  
  get 'tracks/display_map'
  get 'tracks/getallroutesformap'
  get 'tracks/getrouteformap'
  get 'tracks/getroutes'
  post 'tracks/updatelocation'
  get 'tracks/deleteroute'
  
    
  devise_for :users, :controllers => {sessions: 'sessions', :passwords => "passwords"}
  

resources :users

  resources :schools

  resources :stops do
  collection do
      post  :create_route_stops
    end
  end

  resources :routes do
   collection do
      get  :user_routes
    end
  end

  resources :devices

  resources :vehicles do
   collection do
      get  :user_vehicles
    end
  end
  root 'tracks#display_map'
  

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :school
  has_one :device
  has_many :routes
  validates :registration_no, :uniqueness => true
  validates :vehicle_type,:registration_no, :school_id, :presence => true
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:index, :show]
  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.where(:id => school_vehicles_ids)
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
    @school = current_user.school
  end

  # GET /vehicles/1/edit
  def edit
    @school = current_user.school
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicles_path, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicles_path, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def user_vehicles
      myUser = User.find_by_id(params["user"])
      if myUser.role == "superuser"
        @vehicles =  Vehicle.all
      else
        @vehicles = myUser.school.vehicles
      end
      render json: {:vehicles=>@vehicles,:message=>"Vehicles Loded Successfully",:success=>"true",:total => @vehicles.count}
  end 
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      unless params["action"]=="user_vehicles"
      params.require(:vehicle).permit(:registration_no, :capacity, :vehicle_type, :school_id)
      end
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
<% if @vehicle.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

	<ul>
		<% @vehicle.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :registration_no %>
	<br>
	<%= f.text_field :registration_no ,:class=> "form-control", :required => true,:placeholder => "Registration No"%>
</div>
<div class="field">
	<%= f.label :capacity %>
	<br>
	<%= f.number_field :capacity ,:class=> "form-control",:placeholder => "Capacity"%>
</div>
<div class="field">
	<%= f.label :vehicle_type %>
	<br>
	<%= f.text_field :vehicle_type ,:class=> "form-control", :required => true,:placeholder => "Vehicle Type"%>
</div>
<div class="field">	
	 <% if current_user.role == "superuser"%>
	<%= f.label :school_id %>
	<br> 	
	<%= f.select(:school_id ,School.all.map {|c| [c.name, c.id]} ,{:prompt => "Select"}, {:class=>"form-control", :required => true})%>
	<%else%>
	<%=f.hidden_field :school_id, :value=> @school.id %>
	<%end%>
</div>
<br>
<div class="actions">
	<%= f.submit "Submit",:class=> "btn btn-primary btn-lg btn-block"%>
</div>

<% end %>

app/views/vehicles/edit.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<h1>Editing Vehicle</h1>

		<%= render 'form' %>

		<%= link_to 'Show', @vehicle %> |
		<%= link_to 'Back', vehicles_path %>
	</div>
</div>

app/views/vehicles/index.html.erb
<h1>Listing Vehicles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Registration no</th>
      <th>Capacity</th>
      <th>Vehicle Type</th>
      <th>School</th>
       <% if current_user.role == "superuser" || current_user.role == "admin"%>
        <th colspan="3"></th>
      <%end%>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.registration_no %></td>
        <td><%= vehicle.capacity %></td>
        <td><%= vehicle.vehicle_type %></td>
        <td><%= vehicle.school.name %></td>
         <% if current_user.role == "superuser" || current_user.role == "admin"%>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <%end%>
         <% if current_user.role == "superuser"%>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.role == "superuser" || current_user.role == "admin"%>
<%= link_to 'New Vehicle', new_vehicle_path %>
<%end%>

app/views/vehicles/new.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4 well">
		<h1>New Vehicle</h1>

		<%= render 'form' %>

		<%= link_to 'Back', vehicles_path %>
	</div>
</div>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Registration no:</strong>
  <%= @vehicle.registration_no %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @vehicle.capacity %>
</p>

<p>
  <strong>Vehicle Type:</strong>
  <%= @vehicle.vehicle_type %>
</p>
<% if current_user.role == "superuser" || current_user.role == "admin"%>
<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%end%>
<%= link_to 'Back', vehicles_path %>