config/routes.rb
Rails.application.routes.draw do

  get 'admin_panel/users'

  get 'admin_panel/edit_role'
  post 'admin_panel/update_role'
  
  get 'tracks/display_map'
  get 'tracks/getallroutesformap'
  get 'tracks/getrouteformap'
  get 'tracks/getroutes'
  post 'tracks/updatelocation'
  get 'tracks/deleteroute'
  
    
  devise_for :users, :controllers => {sessions: 'sessions', :passwords => "passwords"}
  

resources :users

  resources :schools

  resources :stops do
  collection do
      post  :create_route_stops
    end
  end

  resources :routes do
   collection do
      get  :user_routes
    end
  end

  resources :devices

  resources :vehicles do
   collection do
      get  :user_vehicles
    end
  end
  root 'tracks#display_map'
  

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Gps Tracker</a>
    </div>

 <% if user_signed_in? %>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<li><%=link_to "Tracks",tracks_display_map_path%></li>
      	<li><%=link_to "Vehicles", vehicles_path%></li>
        <li><%=link_to "Routes", routes_path%></li>
        <li><%=link_to "Devices", devices_path%></li>
        <li><%=link_to "Stops", stops_path%></li>
        <li><%=link_to "Schools", schools_path%></li>
         <% if current_user.role == "superuser" || current_user.role == "admin"%>
        <li><%=link_to "Users", admin_panel_users_path%></li>
        <%end%>
      </ul>
   <%end%>
      
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
      
      <ul class="nav navbar-nav navbar-right">
       <% if user_signed_in? %>
        <li class="dropdown">        	
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %>&nbsp;<i class="glyphicon glyphicon-user"></i>&nbsp; <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        <% else %>
				<li>
					<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
				</li>
				<li>
					<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
				</li>
        <% end %>
      </ul>
      
      
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gpstracker</title>
  <script src="//maps.google.com/maps/api/js?v=3&sensor=false&libraries=adsense"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/cerulean/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/header"%>
<div class="container">
	       <% if notice %>
			<div class="alert  alert alert-warning">
				<a href="#" class="close" data-dismiss="alert">&times;</a>
				<%= raw(notice.titleize) %>
			</div>
			<% end %>
			<% if alert %>
			<div class="alert  alert-danger">
				<a href="#" class="close" data-dismiss="alert">&times;</a>
				<%= raw(alert.titleize) %>
			</div>
			<% end %>
<%= yield %>
</div>

</body>
</html>